package it.rotaliano.jdbc.salesforce.statement.processor;

import it.rotaliano.jdbc.salesforce.delegates.PartnerService;
import it.rotaliano.jdbc.salesforce.resultset.CachedResultSet;
import it.rotaliano.jdbc.salesforce.resultset.CommandLogCachedResultSet;
import it.rotaliano.jdbc.salesforce.statement.ForcePreparedStatement;
import com.sforce.soap.partner.IError;
import com.sforce.soap.partner.ISaveResult;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

public class InsertQueryProcessor {

    public static CachedResultSet processQuery(ForcePreparedStatement statement, List<Object> parameters,
        PartnerService partnerService, InsertQueryAnalyzer insertQueryAnalyzer) {

        String fromObjectName = insertQueryAnalyzer.getFromObjectName();
        int[] updateCount = {0};

        CommandLogCachedResultSet resultSet = DmlResultHandler.execute(
            "create " + fromObjectName + " entities",
            rs -> {
                ISaveResult[] records = partnerService.createRecords(
                    fromObjectName, insertQueryAnalyzer.getRecords(parameters));
                for (ISaveResult result : records) {
                    if (result.isSuccess()) {
                        if (statement.hasAutoGeneratedKeys()) {
                            rs.setId(result.getId());
                        }
                        updateCount[0]++;
                    } else {
                        rs.addWarning(fromObjectName + " failed to create with error="
                            + Arrays.stream(result.getErrors()).map(IError::getMessage)
                                .collect(Collectors.joining(",")));
                    }
                }
                statement.setUpdateCount(updateCount[0]);
                statement.setResultSet(rs);
            });

        return resultSet;
    }
}
