package it.rotaliano.jdbc.salesforce.statement.processor;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

import it.rotaliano.jdbc.salesforce.delegates.PartnerService;
import it.rotaliano.jdbc.salesforce.resultset.CachedResultSet;
import it.rotaliano.jdbc.salesforce.statement.ForcePreparedStatement;
import com.sforce.soap.partner.DeleteResult;
import com.sforce.soap.partner.Error;
import com.sforce.soap.partner.SaveResult;
import com.sforce.ws.ConnectionException;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.mockito.junit.jupiter.MockitoSettings;
import org.mockito.quality.Strictness;

@ExtendWith(MockitoExtension.class)
@MockitoSettings(strictness = Strictness.LENIENT)
class DmlQueryProcessorTest {

    @Mock private ForcePreparedStatement statement;
    @Mock private PartnerService partnerService;
    @Mock private InsertQueryAnalyzer insertAnalyzer;
    @Mock private UpdateQueryAnalyzer updateAnalyzer;
    @Mock private DeleteQueryAnalyzer deleteAnalyzer;
    @Mock private SaveResult saveResult;
    @Mock private DeleteResult deleteResult;
    @Mock private Error error;

    @BeforeEach
    void setUp() {
        when(error.getMessage()).thenReturn("SF error detail");
    }

    // -------------------------------------------------------------------------
    @Nested
    @DisplayName("InsertQueryProcessor tests")
    class InsertQueryProcessorTests {

        @Test
        @DisplayName("successful insert increments updateCount and sets resultSet")
        void testSuccessfulInsert() throws Exception {
            when(insertAnalyzer.getFromObjectName()).thenReturn("Account");
            when(insertAnalyzer.getRecords(any())).thenReturn(List.of(Map.of("Name", "Test")));
            when(saveResult.isSuccess()).thenReturn(true);
            when(saveResult.getId()).thenReturn("001xx");
            when(partnerService.createRecords(eq("Account"), any())).thenReturn(new SaveResult[]{saveResult});

            CachedResultSet rs = InsertQueryProcessor.processQuery(statement, List.of(), partnerService, insertAnalyzer);

            assertNotNull(rs);
            verify(statement).setUpdateCount(1);
            verify(statement).setResultSet(rs);
        }

        @Test
        @DisplayName("failed insert adds warning, does not increment updateCount")
        void testFailedInsert() throws Exception {
            when(insertAnalyzer.getFromObjectName()).thenReturn("Account");
            when(insertAnalyzer.getRecords(any())).thenReturn(List.of(Map.of("Name", "Bad")));
            when(saveResult.isSuccess()).thenReturn(false);
            when(saveResult.getErrors()).thenReturn(new Error[]{error});
            when(partnerService.createRecords(eq("Account"), any())).thenReturn(new SaveResult[]{saveResult});

            CachedResultSet rs = InsertQueryProcessor.processQuery(statement, List.of(), partnerService, insertAnalyzer);

            assertNotNull(rs);
            verify(statement).setUpdateCount(0);
            assertNotNull(rs.getWarnings());
            assertTrue(rs.getWarnings().getMessage().contains("failed to create"));
        }

        @Test
        @DisplayName("ConnectionException adds warning and does not throw")
        void testInsertConnectionException() throws Exception {
            when(insertAnalyzer.getFromObjectName()).thenReturn("Account");
            when(insertAnalyzer.getRecords(any())).thenReturn(List.of());
            when(partnerService.createRecords(any(), any())).thenThrow(new ConnectionException("network error"));

            CachedResultSet rs = InsertQueryProcessor.processQuery(statement, List.of(), partnerService, insertAnalyzer);

            assertNotNull(rs);
            assertNotNull(rs.getWarnings());
            assertTrue(rs.getWarnings().getMessage().contains("network error"));
        }

        @Test
        @DisplayName("auto-generated keys: id is set when hasAutoGeneratedKeys is true")
        void testInsertWithAutoGeneratedKeys() throws Exception {
            when(statement.hasAutoGeneratedKeys()).thenReturn(true);
            when(insertAnalyzer.getFromObjectName()).thenReturn("Account");
            when(insertAnalyzer.getRecords(any())).thenReturn(List.of(Map.of("Name", "Test")));
            when(saveResult.isSuccess()).thenReturn(true);
            when(saveResult.getId()).thenReturn("001generatedId");
            when(partnerService.createRecords(eq("Account"), any())).thenReturn(new SaveResult[]{saveResult});

            CachedResultSet rs = InsertQueryProcessor.processQuery(statement, List.of(), partnerService, insertAnalyzer);

            assertTrue(rs.next());
            assertEquals("001generatedId", rs.getString("Id"));
        }

        @Test
        @DisplayName("no auto-generated keys: id row not added when hasAutoGeneratedKeys is false")
        void testInsertWithoutAutoGeneratedKeys() throws Exception {
            when(statement.hasAutoGeneratedKeys()).thenReturn(false);
            when(insertAnalyzer.getFromObjectName()).thenReturn("Account");
            when(insertAnalyzer.getRecords(any())).thenReturn(List.of(Map.of("Name", "Test")));
            when(saveResult.isSuccess()).thenReturn(true);
            when(saveResult.getId()).thenReturn("001generatedId");
            when(partnerService.createRecords(eq("Account"), any())).thenReturn(new SaveResult[]{saveResult});

            CachedResultSet rs = InsertQueryProcessor.processQuery(statement, List.of(), partnerService, insertAnalyzer);

            assertFalse(rs.next());
        }
    }

    // -------------------------------------------------------------------------
    @Nested
    @DisplayName("UpdateQueryProcessor tests")
    class UpdateQueryProcessorTests {

        @Test
        @DisplayName("successful update increments updateCount and sets id")
        void testSuccessfulUpdate() throws Exception {
            when(updateAnalyzer.getFromObjectName()).thenReturn("Contact");
            when(updateAnalyzer.getRecords(any())).thenReturn(List.of(Map.of("Id", "003xx", "Name", "New")));
            when(saveResult.isSuccess()).thenReturn(true);
            when(saveResult.getId()).thenReturn("003xx");
            when(partnerService.saveRecords(eq("Contact"), any())).thenReturn(new SaveResult[]{saveResult});

            CachedResultSet rs = UpdateQueryProcessor.processQuery(statement, List.of(), partnerService, updateAnalyzer);

            assertNotNull(rs);
            verify(statement).setUpdateCount(1);
            assertTrue(rs.next());
            assertEquals("003xx", rs.getString("Id"));
        }

        @Test
        @DisplayName("failed update adds warning")
        void testFailedUpdate() throws Exception {
            when(updateAnalyzer.getFromObjectName()).thenReturn("Contact");
            when(updateAnalyzer.getRecords(any())).thenReturn(List.of(Map.of("Id", "003xx")));
            when(saveResult.isSuccess()).thenReturn(false);
            when(saveResult.getErrors()).thenReturn(new Error[]{error});
            when(partnerService.saveRecords(eq("Contact"), any())).thenReturn(new SaveResult[]{saveResult});

            CachedResultSet rs = UpdateQueryProcessor.processQuery(statement, List.of(), partnerService, updateAnalyzer);

            assertNotNull(rs);
            verify(statement).setUpdateCount(0);
            assertNotNull(rs.getWarnings());
            assertTrue(rs.getWarnings().getMessage().contains("failed to update"));
        }

        @Test
        @DisplayName("ConnectionException adds warning and does not throw")
        void testUpdateConnectionException() throws Exception {
            when(updateAnalyzer.getFromObjectName()).thenReturn("Contact");
            when(updateAnalyzer.getRecords(any())).thenReturn(List.of());
            when(partnerService.saveRecords(any(), any())).thenThrow(new ConnectionException("timeout"));

            CachedResultSet rs = UpdateQueryProcessor.processQuery(statement, List.of(), partnerService, updateAnalyzer);

            assertNotNull(rs);
            assertNotNull(rs.getWarnings());
            assertTrue(rs.getWarnings().getMessage().contains("timeout"));
        }
    }

    // -------------------------------------------------------------------------
    @Nested
    @DisplayName("DeleteQueryProcessor tests")
    class DeleteQueryProcessorTests {

        @Test
        @DisplayName("successful delete sets id in result")
        void testSuccessfulDelete() throws Exception {
            when(deleteAnalyzer.getFromObjectName()).thenReturn("Lead");
            when(deleteAnalyzer.getRecords(any())).thenReturn(List.of("005xx"));
            when(deleteResult.isSuccess()).thenReturn(true);
            when(deleteResult.getId()).thenReturn("005xx");
            when(partnerService.deleteRecords(any())).thenReturn(new DeleteResult[]{deleteResult});

            CachedResultSet rs = DeleteQueryProcessor.processQuery(List.of(), partnerService, deleteAnalyzer);

            assertNotNull(rs);
            assertTrue(rs.next());
            assertEquals("005xx", rs.getString("Id"));
        }

        @Test
        @DisplayName("failed delete adds warning")
        void testFailedDelete() throws Exception {
            when(deleteAnalyzer.getFromObjectName()).thenReturn("Lead");
            when(deleteAnalyzer.getRecords(any())).thenReturn(List.of("005xx"));
            when(deleteResult.isSuccess()).thenReturn(false);
            when(deleteResult.getErrors()).thenReturn(new Error[]{error});
            when(partnerService.deleteRecords(any())).thenReturn(new DeleteResult[]{deleteResult});

            CachedResultSet rs = DeleteQueryProcessor.processQuery(List.of(), partnerService, deleteAnalyzer);

            assertNotNull(rs);
            assertNotNull(rs.getWarnings());
            assertTrue(rs.getWarnings().getMessage().contains("failed to delete"));
        }

        @Test
        @DisplayName("ConnectionException adds warning and does not throw")
        void testDeleteConnectionException() throws Exception {
            when(deleteAnalyzer.getFromObjectName()).thenReturn("Lead");
            when(deleteAnalyzer.getRecords(any())).thenReturn(List.of("005xx"));
            when(partnerService.deleteRecords(any())).thenThrow(new ConnectionException("service unavailable"));

            CachedResultSet rs = DeleteQueryProcessor.processQuery(List.of(), partnerService, deleteAnalyzer);

            assertNotNull(rs);
            assertNotNull(rs.getWarnings());
            assertTrue(rs.getWarnings().getMessage().contains("service unavailable"));
        }
    }
}
