package it.rotaliano.jdbc.salesforce.statement;

import it.rotaliano.jdbc.salesforce.ForceDriver;
import it.rotaliano.jdbc.salesforce.cache.CacheConfig;
import it.rotaliano.jdbc.salesforce.connection.ForceConnection;
import it.rotaliano.jdbc.salesforce.delegates.ForceResultField;
import it.rotaliano.jdbc.salesforce.delegates.PartnerService;
import it.rotaliano.jdbc.salesforce.exceptions.SalesforceRuntimeException;
import it.rotaliano.jdbc.salesforce.metadata.ColumnMap;
import it.rotaliano.jdbc.salesforce.metadata.ForceDatabaseMetaData;
import it.rotaliano.jdbc.salesforce.metadata.TypeInfo;
import it.rotaliano.jdbc.salesforce.resultset.CachedResultSet;
import it.rotaliano.jdbc.salesforce.statement.processor.QueryAnalyzer;
import it.rotaliano.jdbc.salesforce.statement.processor.SoqlQueryAnalyzer;
import it.rotaliano.jdbc.salesforce.statement.processor.StatementContext;
import it.rotaliano.jdbc.salesforce.statement.processor.StatementProcessor;
import it.rotaliano.jdbc.salesforce.statement.processor.StatementProcessorFactory;
import it.rotaliano.jdbc.salesforce.utils.FieldDefTree;
import com.sforce.ws.ConnectionException;
import java.math.BigDecimal;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.sql.*;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Stream;
import javax.sql.rowset.RowSetMetaDataImpl;
import lombok.Setter;
import lombok.extern.slf4j.Slf4j;
import org.apache.commons.lang3.StringUtils;
import org.ehcache.Cache;

@Slf4j
public class ForcePreparedStatement extends AbstractPreparedStatement implements Iterator<List<ColumnMap<String, Object>>> {

    private static final Pattern CACHE_HINT = Pattern.compile("(?is)\\A\\s*(CACHE\\s*(GLOBAL|SESSION)).*");

    protected enum CacheMode {
        NO_CACHE, GLOBAL, SESSION
    }

    private String soqlQuery;
    private final ForceConnection connection;
    private PartnerService partnerService;
    private ResultSetMetaData metadata;
    private int fetchSize;
    private int maxRows;
    private final List<Object> parameters = new ArrayList<>();
    private CacheMode cacheMode;
    @Setter
    private int updateCount = -1;
    private boolean updateCountReturned = false;
    @Setter
    private ResultSet resultSet;
    private boolean resultSetReturned = false;
    private SQLWarning warnings = new SQLWarning();
    private boolean neverQueriedMore;
    private String queryMoreLocator;
    private int autoGeneratedKeys;
    private int fetchDirection;

    private static final CacheConfig cacheDb = CacheConfig.getInstance();
    private static final Cache<String, CachedResultSet> dataCache = cacheDb.getDataCache();

    public ForcePreparedStatement(ForceConnection connection) {
        if (connection == null) {
            throw new IllegalArgumentException("Invalid value. Connection cannot be null.");
        }
        this.connection = connection;
        this.fetchDirection = ResultSet.FETCH_FORWARD;
        this.autoGeneratedKeys = Statement.NO_GENERATED_KEYS;
        this.partnerService = connection.getPartnerService();
    }

    public ForcePreparedStatement(ForceConnection connection, String soql) {
        this(connection);
        this.soqlQuery = soql;
    }

    public ForcePreparedStatement(ForceConnection connection, String soql, int autoGeneratedKeys) {
        this(connection, soql);
        this.autoGeneratedKeys = autoGeneratedKeys;
    }

    @Override
    public ResultSet executeQuery() throws SQLException {
        executeInternal(soqlQuery, Statement.NO_GENERATED_KEYS);
        return this.resultSet;
    }

    private void executeInternal(String soql, int autoGeneratedKeys) throws SQLException {
        this.metadata = null;
        this.queryAnalyzer = null;
        this.soqlQueryAnalyzer = null;
        this.resultSet = null;
        this.fieldDefinitions = null;
        this.autoGeneratedKeys = autoGeneratedKeys;
        this.updateCount = -1;
        this.updateCountReturned = false;
        this.resultSetReturned = false;
        setCacheMode(soql);
        this.resultSet = cacheMode == CacheMode.NO_CACHE
                ? query()
                : loadFromDataCache();
    }

    private CachedResultSet query() throws SQLException {
        log.trace("[PrepStat] query IMPLEMENTED {}", soqlQuery);

        StatementContext context = StatementContext.from(
                this, soqlQuery, getParameters(), partnerService, getQueryAnalyzer());

        StatementProcessor processor = StatementProcessorFactory.getProcessor(context);
        return processor.process(context);
    }

    public boolean hasAutoGeneratedKeys() {
        return this.autoGeneratedKeys == Statement.RETURN_GENERATED_KEYS;
    }

    /**
     * Returns whether cache is disabled for this query.
     */
    public boolean isNoCacheMode() {
        return cacheMode == CacheMode.NO_CACHE;
    }

    /**
     * Sets the neverQueriedMore flag for streaming queries.
     */
    public void setNeverQueriedMore(boolean value) {
        this.neverQueriedMore = value;
    }

    /**
     * Prepares and returns the query string ready for execution.
     */
    public String prepareQueryForExecution() {
        soqlQuery = prepareQuery(getSoqlQueryAnalyzer().getSoqlQueryString());
        return soqlQuery;
    }

    @Override
    public boolean hasNext() {
        return this.neverQueriedMore || this.queryMoreLocator != null;
    }

    @Override
    public List<ColumnMap<String, Object>> next() {
        try {
            Map.Entry<List<List<ForceResultField>>, String> resultEntry;
            if (this.neverQueriedMore) {
                this.neverQueriedMore = false;
                resultEntry = partnerService.queryStart(soqlQuery, getRootEntityFieldDefinitions());
            } else if (this.queryMoreLocator != null) {
                resultEntry = partnerService.queryMore(this.queryMoreLocator, getRootEntityFieldDefinitions());
            } else {
                return Collections.emptyList();
            }
            this.queryMoreLocator = resultEntry.getValue();
            List<ColumnMap<String, Object>> result = Collections.synchronizedList(new LinkedList<>());
            Optional.ofNullable(resultEntry.getKey())
                    .orElseGet(Collections::emptyList)
                    .forEach(rec -> result.add(convertToColumnMap(rec)));
            return result;
        } catch (ConnectionException e) {
            throw new SalesforceRuntimeException("Failed to fetch next batch of query results", e);
        }
    }

    private String prepareQuery(String query) {
        log.trace("[PrepStat] prepareQuery IMPLEMENTED {}", query);
        query = preprocessQuery(query);
        return setParams(query);
    }

    private String preprocessQuery(String soqlQuery) {
        // Preprocess some sugar like Date Literals into SOQL format
        // '{ts 2021-10-12 00:00:12Z}'
        // '{ts 2021-10-12T00:00:12Z}'
        if (soqlQuery == null) {
            return soqlQuery;
        }
        String soqlQueryProcessed = soqlQuery;
        if (soqlQuery.contains("{ts")) {
            soqlQueryProcessed = soqlQuery.trim()
                    .replaceAll(
                            "'\\{ts\\s*(\\d{4}-\\d{2}-\\d{2})(T|\\s)(\\d{2}:\\d{2}:\\d{2})(Z|[+-]\\d{3,4}|)(\\.\\d+)?\\s*}'",
                            "$1T$3$4");
        }
        return soqlQueryProcessed;
    }

    public ColumnMap<String, Object> convertToColumnMap(List<ForceResultField> recordFields) {
        ColumnMap<String, Object> columnMap = new ColumnMap<>();
        // Flatten not only child records, but also Lists of Lists - for Relations - list of subrecords
        recordFields = flatten(recordFields);
        recordFields.stream()
                .map(field -> field == null ? new ForceResultField() : field)
                .forEach(field -> {
                    TypeInfo typeInfo = TypeInfo.OTHER_TYPE_INFO;
                    if (field.getFieldType() != null) {
                        typeInfo = TypeInfo.lookupTypeInfo(field.getFieldType());
                    }
                    if (typeInfo == TypeInfo.OTHER_TYPE_INFO) {
                        typeInfo = findColumnType(field.getName());
                    }
                    String columnLabel = findColumnLabel(field.getName());
                    columnMap.put(field.getFullName(), columnLabel, field.getValue(), typeInfo);
                });
        return columnMap;
    }

    private TypeInfo findColumnType(String name) {
        if (name == null) {
            return TypeInfo.OTHER_TYPE_INFO;
        }
        try {
            for (int i = 1; i <= metadata.getColumnCount(); i++) {
                if (name.equalsIgnoreCase(metadata.getColumnName(i))) {
                    return TypeInfo.lookupTypeInfo(metadata.getColumnTypeName(i));
                }
            }
            String[] prefix = StringUtils.split(name, '.');
            if (prefix.length > 0) {
                name = String.join(".", List.of(prefix).subList(1, prefix.length));
                for (int i = 1; i <= metadata.getColumnCount(); i++) {
                    if (name.equalsIgnoreCase(metadata.getColumnName(i))) {
                        return TypeInfo.lookupTypeInfo(metadata.getColumnTypeName(i));
                    }
                }
            }
        } catch (SQLException e) {
            // ignore
        }
        return TypeInfo.OTHER_TYPE_INFO;
    }

    private String findColumnLabel(String name) {
        if (name == null) {
            return null;
        }
        try {
            for (int i = 1; i <= metadata.getColumnCount(); i++) {
                if (name.equalsIgnoreCase(metadata.getColumnName(i))) {
                    return metadata.getColumnLabel(i);
                }
            }
        } catch (SQLException e) {
            // ignore
        }
        return name;
    }

    protected void setCacheMode(String query) {
        Matcher matcher = CACHE_HINT.matcher(query);
        if (matcher.matches()) {
            String mode = matcher.group(2);
            String hint = matcher.group(1);
            this.soqlQuery = query.replaceFirst(hint, "");
            this.cacheMode = CacheMode.valueOf(mode.toUpperCase());
        } else {
            this.soqlQuery = query;
            this.cacheMode = CacheMode.NO_CACHE;
        }
    }

    private String getCacheKey() {
        String preparedQuery = prepareQuery(soqlQuery);
        String key = cacheMode == CacheMode.GLOBAL
                ? preparedQuery
                : connection.getUUID() + preparedQuery;
        return sha256(key);
    }

    private String sha256(final String key) {
        try {
            final MessageDigest digest = MessageDigest.getInstance("SHA-256");
            final byte[] hash = digest.digest(key.getBytes(StandardCharsets.UTF_8));
            final StringBuilder hexString = new StringBuilder();
            for (final byte b : hash) {
                final String hex = Integer.toHexString(0xff & b);
                if (hex.length() == 1) {
                    hexString.append('0');
                }
                hexString.append(hex);
            }
            return hexString.toString();
        } catch (Exception ex) {
            return key;
        }
    }

    public List<Object> getParameters() {
        log.trace("[PrepStat] getParameters IMPLEMENTED {}", soqlQuery);
        int paramsCountInQuery = StringUtils.countMatches(soqlQuery, '?');
        log.debug("[PrepStat] getParameters - {}/{} parameters", paramsCountInQuery, parameters.size());
        if (parameters.size() < paramsCountInQuery) {
            parameters.addAll(Collections.nCopies(paramsCountInQuery - parameters.size(), null));
        }
        return parameters;
    }

    protected String setParams(String soql) {
        log.trace("[PrepStat] setParams IMPLEMENTED {}", soql);
        String result = soql;
        for (Object param : getParameters()) {
            String paramRepresentation = SoqlParameterConverter.convertToSoqlParam(param);
            result = result.replaceFirst("\\?", paramRepresentation);
        }
        return result;
    }

    public static ResultSetMetaData createMetaData(ColumnMap<String, Object> row) {
        if (row == null) {
            return null;
        }
        try {
            log.trace("[PrepStat] dummyMetaData IMPLEMENTED");
            RowSetMetaDataImpl result = new RowSetMetaDataImpl();
            int columnsCount = row.size();
            result.setColumnCount(columnsCount);
            for (int i = 1; i <= columnsCount; i++) {
                String fieldName = row.getColumnNames().get(i - 1);
                result.setAutoIncrement(i, false);
                result.setColumnName(i, fieldName);
                result.setColumnLabel(i, fieldName);
                TypeInfo typeInfo = row.getTypes().get(i - 1);
                log.trace(
                        "[PrepStat] createMetaData (" + i + ") " + fieldName + " : " + typeInfo.getTypeName() + " => "
                                + typeInfo.getSqlDataType());
                result.setColumnType(i, typeInfo.getSqlDataType());
                result.setColumnTypeName(i, typeInfo.getTypeName());
                result.setPrecision(i, typeInfo.getPrecision());
                result.setSchemaName(i, ForceDatabaseMetaData.DEFAULT_SCHEMA);
                result.setCatalogName(i, ForceDatabaseMetaData.DEFAULT_CATALOG);
                result.setTableName(i, null);
                result.setCaseSensitive(i, false);
            }
            return result;
        } catch (Exception e) {
            // Ignore for metadata - just return empty
            log.warn("Failed to compile dummy metadata information", e);
            return null;
        }
    }

    private ResultSetMetaData loadMetaData() throws SQLException {
        try {
            log.trace("[PrepStat] loadMetaData IMPLEMENTED");
            if (metadata == null) {
                RowSetMetaDataImpl result = new RowSetMetaDataImpl();
                SoqlQueryAnalyzer analyzer = getSoqlQueryAnalyzer();
                FieldDefTree rootFieldDefinitions = getRootEntityFieldDefinitions();
                List<FieldDef> resultFieldDefinitions = rootFieldDefinitions.flatten();
                int columnsCount = resultFieldDefinitions.size();
                result.setColumnCount(columnsCount);
                for (int i = 1; i <= columnsCount; i++) {
                    FieldDef field = resultFieldDefinitions.get(i - 1);
                    result.setAutoIncrement(i, false);
                    result.setColumnName(i, field.getFullName());
                    result.setColumnLabel(i, field.getAlias());
                    String forceTypeName = field.getType();
                    TypeInfo typeInfo = TypeInfo.lookupTypeInfo(forceTypeName);
                    result.setColumnType(i, typeInfo.getSqlDataType());
                    result.setColumnTypeName(i, typeInfo.getTypeName());
                    result.setPrecision(i, typeInfo.getPrecision());
                    result.setSchemaName(i, ForceDatabaseMetaData.DEFAULT_SCHEMA);
                    result.setCatalogName(i, ForceDatabaseMetaData.DEFAULT_CATALOG);
                    result.setTableName(i, analyzer.getFromObjectName());
                    result.setCaseSensitive(i, false);
                }
                metadata = result;
            }
            return metadata;
        } catch (RuntimeException e) {
            throw new SQLException(e.getCause() != null ? e.getCause() : e);
        }
    }

    private <T> List<T> flatten(List<T> listWithLists) {
        return listWithLists.stream()
                .flatMap(
                        def -> def instanceof Collection
                                ? flatten((List<T>) def).stream() // MultiLevel flattening
                                : Stream.of(def)
                ).toList();
    }

    private FieldDefTree fieldDefinitions;

    public FieldDefTree getRootEntityFieldDefinitions() {
        log.trace("[PrepStat] getFieldDefinitions IMPLEMENTED ");
        if (fieldDefinitions == null) {
            fieldDefinitions = getSoqlQueryAnalyzer().getFieldDefinitions();
            log.debug("[PrepStat] getFieldDefinitions:\n {}", fieldDefinitions.toTree());
        }
        return fieldDefinitions;
    }

    private QueryAnalyzer queryAnalyzer;
    private SoqlQueryAnalyzer soqlQueryAnalyzer;

    private QueryAnalyzer getQueryAnalyzer() {
        if (queryAnalyzer == null) {
            queryAnalyzer = new QueryAnalyzer(soqlQuery, this::runResolveSubselect, partnerService);
        }
        return queryAnalyzer;
    }

    private SoqlQueryAnalyzer getSoqlQueryAnalyzer() {
        if (soqlQueryAnalyzer == null) {
            soqlQueryAnalyzer = new SoqlQueryAnalyzer(getQueryAnalyzer());
            if (soqlQueryAnalyzer.isExpandedStarSyntaxForFields()) {
                this.soqlQuery = soqlQueryAnalyzer.getSoqlQueryString();
                log.debug("[PrepStat] Expanded Star Syntax to {}", soqlQuery);
            }
        }
        return soqlQueryAnalyzer;
    }

    private List<Map<String, Object>> runResolveSubselect(String soql, List<Object> parameters) {
        List<Map<String, Object>> results = new ArrayList<>();
        log.debug("Resolving subselect \n{}", soql);
        try {
            ForcePreparedStatement forcePreparedStatement = new ForcePreparedStatement(connection, soql);
            forcePreparedStatement.addParameters(parameters);
            ResultSet rs = forcePreparedStatement.query();

            while (rs.next()) {
                // LinkedHashMap is needed to save the order of the fields
                Map<String, Object> rec = new LinkedHashMap<>();
                results.add(rec);
                for (int i = 0; i < rs.getMetaData().getColumnCount(); i++) {
                    rec.put(rs.getMetaData().getColumnName(i + 1), rs.getString(i + 1));
                }
            }
            log.debug("  {} records resolved with {} columns", results.size(), rs.getMetaData().getColumnCount());
        } catch (Exception e) {
            log.warn("Failed to resolve sub-select \n{}", soql, e);
            this.warnings.addSuppressed(new SQLWarning("Failed to resolve sub-select \n" + soql, e));
            throw new IllegalArgumentException("Failed to resolve sub-select: " + e.getMessage());
        }

        return results;
    }

    @Override
    public ParameterMetaData getParameterMetaData() {
        return new ParameterMetadataImpl(parameters, soqlQuery);
    }

    public ResultSetMetaData getMetaData() throws SQLException {
        log.trace("[PrepStat] getMetaData IMPLEMENTED ");
        return cacheMode == CacheMode.NO_CACHE
                ? loadMetaData()
                : loadFromMetaDataCache();
    }

    private ResultSetMetaData loadFromMetaDataCache() throws SQLException {
        String key = getCacheKey();
        if (dataCache.containsKey(key)) {
            CachedResultSet value = dataCache.get(key);
            value.beforeFirst();
            return value.getMetaData();
        }

        ResultSetMetaData value;
        value = loadMetaData();

        this.metadata = value;
        return value;
    }

    private synchronized ResultSet loadFromDataCache() throws SQLException {
        CachedResultSet value;
        String key = getCacheKey();
        if (dataCache.containsKey(key)) {
            value = dataCache.get(key);
            value.beforeFirst();
            return value;
        }

        value = query();
        dataCache.put(key, value);
        return value;
    }

    public boolean reconnect(String url, String userName, String userPass) throws ConnectionException {
        log.trace("[PrepStat] RECONNECT IMPLEMENTED newUserName={} url={}", userName, ForceDriver.sanitizeUrl(url));
        boolean updated = connection.updatePartnerConnection(url, userName, userPass);
        this.partnerService = connection.getPartnerService();
        return updated;
    }

    @Override
    public void setFetchSize(int rows) {
        this.fetchSize = rows;
    }

    @Override
    public int getFetchSize() {
        return fetchSize;
    }

    @Override
    public void setMaxRows(int max) {
        this.maxRows = max;
    }

    @Override
    public int getMaxRows() {
        return maxRows;
    }

    private void addParameters(List<Object> parameters) {
        this.parameters.addAll(parameters);
    }

    protected void addParameter(int parameterIndex, Object x) {
        log.trace("[PrepStat] addParameter {} IMPLEMENTED", parameterIndex);
        parameterIndex--;
        if (parameters.size() < parameterIndex) {
            parameters.addAll(Collections.nCopies(parameterIndex - parameters.size(), null));
        }
        parameters.add(parameterIndex, x);
    }

    @Override
    public void setBigDecimal(int parameterIndex, BigDecimal x) {
        addParameter(parameterIndex, x);
    }

    @Override
    public void setBoolean(int parameterIndex, boolean x) {
        addParameter(parameterIndex, x);
    }

    @Override
    public void setByte(int parameterIndex, byte x) {
        addParameter(parameterIndex, x);
    }

    @Override
    public void setDate(int parameterIndex, Date x) {
        addParameter(parameterIndex, x);
    }

    @Override
    public void setDouble(int parameterIndex, double x) {
        addParameter(parameterIndex, x);
    }

    @Override
    public void setFloat(int parameterIndex, float x) {
        addParameter(parameterIndex, x);
    }

    @Override
    public void setInt(int parameterIndex, int x) {
        addParameter(parameterIndex, x);
    }

    @Override
    public void setLong(int parameterIndex, long x) {
        addParameter(parameterIndex, x);
    }

    @Override
    public void setNull(int parameterIndex, int sqlType) {
        addParameter(parameterIndex, null);
    }

    @Override
    public void setNull(int paramIndex, int sqlType, String typeName) {
        addParameter(paramIndex, null);
    }

    @Override
    public void setObject(int parameterIndex, Object x) {
        addParameter(parameterIndex, x);
    }

    @Override
    public void setObject(int parameterIndex, Object x, int targetSqlType) {
        addParameter(parameterIndex, x);
    }

    @Override
    public void setObject(int parameterIndex, Object x, int targetSqlType, int scaleOrLength) {
        addParameter(parameterIndex, x);
    }

    @Override
    public void setShort(int parameterIndex, short x) {
        addParameter(parameterIndex, x);
    }

    @Override
    public void setString(int parameterIndex, String x) {
        addParameter(parameterIndex, x);
    }

    @Override
    public void setTime(int parameterIndex, Time x) {
        addParameter(parameterIndex, x);
    }

    @Override
    public void setTimestamp(int parameterIndex, Timestamp x) {
        addParameter(parameterIndex, x);
    }

    @Override
    public ResultSet executeQuery(String sql) throws SQLException {
        log.trace("[PrepStat] executeQuery IMPLEMENTED {}", sql);
        this.soqlQuery = sql;
        this.resultSet = executeQuery();
        return this.resultSet;
    }

    @Override
    public int executeUpdate(String sql) throws SQLException {
        return executeUpdate(sql, this.autoGeneratedKeys);
    }

    @Override
    public void close() {
        parameters.clear();
    }

    @Override
    public SQLWarning getWarnings() throws SQLException {
        return resultSet != null ? resultSet.getWarnings() : warnings;
    }

    @Override
    public void clearWarnings() throws SQLException {
        if (resultSet != null) {
            resultSet.clearWarnings();
        }
        warnings = new SQLWarning();
    }

    @Override
    public boolean execute(String sql) throws SQLException {
        log.trace("[PrepStat] execute IMPLEMENTED {}", sql);
        this.updateCount = -1;
        this.updateCountReturned = false;
        this.soqlQuery = sql;
        this.resultSet = executeQuery();
        this.resultSetReturned = false;
        boolean result = this.updateCount < 0;
        log.trace("[PrepStat] execute IMPLEMENTED ({}){}", result, sql);
        return result;
    }

    @Override
    public ResultSet getResultSet() {
        ResultSet toReturn = updateCount < 0 ? resultSet : null;
        if (this.resultSetReturned) {
            log.trace("[PrepStat] getResultSet IMPLEMENTED Already Returned {}\n {}{}",
                    soqlQuery,
                    (resultSet == null ? " resultSet is NULL" : "resultSet is present"),
                    (toReturn == null ? " -> Not to be returned" : " -> Returning"));
            return null;
        }
        this.resultSetReturned = true;
        log.trace("[PrepStat] getResultSet IMPLEMENTED {}\n {}{}",
                soqlQuery,
                (resultSet == null ? " resultSet is NULL" : "resultSet is present"),
                (toReturn == null ? " -> Not to be returned" : " -> Returning"));
        return toReturn;
    }

    @Override
    public int getUpdateCount() {
        if (this.updateCountReturned) {
            log.trace("[PrepStat] getUpdateCount Already Returned {} IMPLEMENTED", updateCount);
            return -1;
        }
        log.trace("[PrepStat] getUpdateCount {} IMPLEMENTED", updateCount);
        this.updateCountReturned = true;
        return updateCount;
    }

    @Override
    public boolean getMoreResults() throws SQLException {
        if (updateCount >= 0) {
            log.trace("[PrepStat] getMoreResults IMPLEMENTED (false) updateCount={} sql={}", updateCount, soqlQuery);
            return false;
        }
        boolean more = resultSet != null && resultSet.next();
        log.trace("[PrepStat] getMoreResults IMPLEMENTED ({}) updateCount={} sql={}", more, updateCount, soqlQuery);
        return more;
    }

    @Override
    public void setFetchDirection(int direction) throws SQLException {
        if (direction != ResultSet.FETCH_FORWARD && direction != ResultSet.FETCH_REVERSE
                && direction != ResultSet.FETCH_UNKNOWN) {
            throw new SQLException("Unsupported direction: " + direction);
        } else {
            this.fetchDirection = direction;
        }
    }

    @Override
    public int getFetchDirection() {
        return this.fetchDirection;
    }

    @Override
    public Connection getConnection() {
        return connection;
    }

    @Override
    public ResultSet getGeneratedKeys() throws SQLException {
        if (autoGeneratedKeys != Statement.RETURN_GENERATED_KEYS) {
            throw new SQLException(
                    "Cannot return generated keys: query was not set with Statement.RETURN_GENERATED_KEYS");
        }

        return this.resultSet;
    }

    @Override
    public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
        executeInternal(sql, autoGeneratedKeys);
        return this.updateCount;
    }

    @Override
    public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
        return executeUpdate(sql);
    }

    @Override
    public int executeUpdate(String sql, String[] columnNames) throws SQLException {
        return executeUpdate(sql);
    }

    @Override
    public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
        return executeUpdate(sql) > 0;
    }

    @Override
    public boolean execute(String sql, int[] columnIndexes) throws SQLException {
        return executeUpdate(sql) > 0;
    }

    @Override
    public boolean execute(String sql, String[] columnNames) throws SQLException {
        return executeUpdate(sql) > 0;
    }

    @Override
    public <T> T unwrap(Class<T> iface) {
        return iface.isInstance(this) ? iface.cast(this) : null;
    }

    @Override
    public boolean isWrapperFor(Class<?> iface) {
        return iface.isInstance(this);
    }

    @Override
    public int executeUpdate() throws SQLException {
        return executeUpdate(soqlQuery);
    }

    @Override
    public void clearParameters() {
        parameters.clear();
    }

    @Override
    public boolean execute() throws SQLException {
        executeInternal(soqlQuery, autoGeneratedKeys);
        return true;
    }

    @Override
    public void setNString(int parameterIndex, String value) {
        setString(parameterIndex, value);
    }

}
