package it.rotaliano.jdbc.salesforce.statement;

import com.sforce.ws.ConnectionException;
import it.rotaliano.jdbc.salesforce.ForceDriver;
import it.rotaliano.jdbc.salesforce.cache.CacheConfig;
import it.rotaliano.jdbc.salesforce.connection.ForceConnection;
import it.rotaliano.jdbc.salesforce.delegates.ForceResultField;
import it.rotaliano.jdbc.salesforce.delegates.PartnerService;
import it.rotaliano.jdbc.salesforce.exceptions.SalesforceRuntimeException;
import it.rotaliano.jdbc.salesforce.metadata.ColumnMap;
import it.rotaliano.jdbc.salesforce.metadata.ForceDatabaseMetaData;
import it.rotaliano.jdbc.salesforce.metadata.TypeInfo;
import it.rotaliano.jdbc.salesforce.resultset.CachedResultSet;
import it.rotaliano.jdbc.salesforce.statement.processor.QueryAnalyzer;
import it.rotaliano.jdbc.salesforce.statement.processor.SoqlQueryAnalyzer;
import it.rotaliano.jdbc.salesforce.statement.processor.StatementContext;
import it.rotaliano.jdbc.salesforce.statement.processor.StatementProcessor;
import it.rotaliano.jdbc.salesforce.statement.processor.StatementProcessorFactory;
import it.rotaliano.jdbc.salesforce.utils.FieldDefTree;
import java.math.BigDecimal;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.sql.Connection;
import java.sql.Date;
import java.sql.ParameterMetaData;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.Statement;
import java.sql.Time;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Stream;
import javax.sql.rowset.RowSetMetaDataImpl;
import lombok.Setter;
import lombok.extern.slf4j.Slf4j;
import org.apache.commons.lang3.StringUtils;
import org.ehcache.Cache;

/**
 * Salesforce-specific {@link PreparedStatement} implementation.
 *
 * <p>This class adapts JDBC prepared statement behavior to SOQL execution against Salesforce.
 * It supports parameter binding, metadata generation, query preprocessing, optional caching,
 * and execution of both read and write operations through the Salesforce driver pipeline.
 *
 * <p>For {@code SELECT} statements, this class can operate in two modes:
 * cached mode, where the full result is materialized into a {@link CachedResultSet},
 * and non-cached streaming mode, where rows are fetched in batches through the Salesforce API.
 *
 * <p>The statement also acts as an {@link Iterator} of batched result chunks when streaming
 * is used internally for non-cached queries.
 */
@Slf4j
public class ForcePreparedStatement extends AbstractPreparedStatement implements Iterator<List<ColumnMap<String, Object>>> {

    private static final Pattern CACHE_HINT = Pattern.compile("(?is)\\A\\s*(CACHE\\s*(GLOBAL|SESSION)).*");

    /**
     * Cache strategy used for statement execution.
     */
    protected enum CacheMode {
        /**
         * Disables caching for the current query.
         */
        NO_CACHE,
        /**
         * Uses a cache shared across connections for the same prepared query.
         */
        GLOBAL,
        /**
         * Uses a cache scoped to the current connection instance.
         */
        SESSION
    }

    private String soqlQuery;
    private final ForceConnection connection;
    private PartnerService partnerService;
    private ResultSetMetaData metadata;
    private int fetchSize;
    private int maxRows;
    private final List<Object> parameters = new ArrayList<>();
    private CacheMode cacheMode;
    @Setter
    private int updateCount = -1;
    private boolean updateCountReturned = false;
    @Setter
    private ResultSet resultSet;
    private boolean resultSetReturned = false;
    private SQLWarning warnings = new SQLWarning();
    private boolean neverQueriedMore;
    private String queryMoreLocator;
    private int autoGeneratedKeys;
    private int fetchDirection;
    private FieldDefTree fieldDefinitions;
    private QueryAnalyzer queryAnalyzer;
    private SoqlQueryAnalyzer soqlQueryAnalyzer;

    private static final CacheConfig cacheDb = CacheConfig.getInstance();
    private static final Cache<String, CachedResultSet> dataCache = cacheDb.getDataCache();

    /**
     * Creates a statement bound to the given connection.
     *
     * @param connection the owning Salesforce JDBC connection
     * @throws IllegalArgumentException if {@code connection} is {@code null}
     */
    public ForcePreparedStatement(ForceConnection connection) {
        if (connection == null) {
            throw new IllegalArgumentException("Invalid value. Connection cannot be null.");
        }
        this.connection = connection;
        this.fetchDirection = ResultSet.FETCH_FORWARD;
        this.autoGeneratedKeys = Statement.NO_GENERATED_KEYS;
        this.partnerService = connection.getPartnerService();
    }

    /**
     * Creates a statement initialized with the provided SOQL query.
     *
     * @param connection the owning Salesforce JDBC connection
     * @param soql the SOQL query string
     */
    public ForcePreparedStatement(ForceConnection connection, String soql) {
        this(connection);
        this.soqlQuery = soql;
    }

    /**
     * Creates a statement initialized with the provided SOQL query and generated keys mode.
     *
     * @param connection the owning Salesforce JDBC connection
     * @param soql the SOQL query string
     * @param autoGeneratedKeys generated keys flag as defined by {@link Statement}
     */
    public ForcePreparedStatement(ForceConnection connection, String soql, int autoGeneratedKeys) {
        this(connection, soql);
        this.autoGeneratedKeys = autoGeneratedKeys;
    }

    /**
     * Executes the current SOQL query as a query operation.
     *
     * @return the resulting {@link ResultSet}
     * @throws SQLException if execution fails
     */
    @Override
    public ResultSet executeQuery() throws SQLException {
        executeInternal(soqlQuery, Statement.NO_GENERATED_KEYS);
        return this.resultSet;
    }

    /**
     * Resets statement execution state and executes the given SOQL using the requested generated keys mode.
     *
     * @param soql the query to execute
     * @param autoGeneratedKeys generated keys flag as defined by {@link Statement}
     * @throws SQLException if execution fails
     */
    private void executeInternal(String soql, int autoGeneratedKeys) throws SQLException {
        this.metadata = null;
        this.queryAnalyzer = null;
        this.soqlQueryAnalyzer = null;
        this.resultSet = null;
        this.fieldDefinitions = null;
        this.autoGeneratedKeys = autoGeneratedKeys;
        this.updateCount = -1;
        this.updateCountReturned = false;
        this.resultSetReturned = false;
        setCacheMode(soql);
        this.resultSet = cacheMode == CacheMode.NO_CACHE
                ? query()
                : loadFromDataCache();
    }

    /**
     * Executes the current statement through the statement processing pipeline.
     *
     * @return the materialized or streaming-aware result set
     * @throws SQLException if execution fails
     */
    private CachedResultSet query() throws SQLException {
        log.trace("[PrepStat] query IMPLEMENTED {}", soqlQuery);

        StatementContext context = StatementContext.from(
                this, soqlQuery, getParameters(), partnerService, getQueryAnalyzer());

        StatementProcessor processor = StatementProcessorFactory.getProcessor(context);
        return processor.process(context);
    }

    /**
     * Returns whether this statement was configured to expose generated keys.
     *
     * @return {@code true} if generated keys are enabled
     */
    public boolean hasAutoGeneratedKeys() {
        return this.autoGeneratedKeys == Statement.RETURN_GENERATED_KEYS;
    }

    /**
     * Returns whether caching is disabled for the current query.
     *
     * @return {@code true} if the statement is in {@link CacheMode#NO_CACHE} mode
     */
    public boolean isNoCacheMode() {
        return cacheMode == CacheMode.NO_CACHE;
    }

    /**
     * Sets the internal flag indicating that the first streaming batch has not been fetched yet.
     *
     * @param value the new flag value
     */
    public void setNeverQueriedMore(boolean value) {
        this.neverQueriedMore = value;
    }

    /**
     * Builds the final SOQL string to be sent to Salesforce.
     *
     * <p>This includes query normalization, optional field expansion, preprocessing of supported
     * literal syntaxes, and replacement of JDBC parameters with SOQL-safe literal values.
     *
     * @return the SOQL string ready for execution
     */
    public String prepareQueryForExecution() {
        soqlQuery = prepareQuery(getSoqlQueryAnalyzer().getSoqlQueryString());
        return soqlQuery;
    }

    /**
     * Indicates whether another streaming batch is available.
     *
     * @return {@code true} if the initial batch or a subsequent batch can still be fetched
     */
    @Override
    public boolean hasNext() {
        return this.neverQueriedMore || this.queryMoreLocator != null;
    }

    /**
     * Fetches the next batch of rows for a streaming query.
     *
     * <p>If streaming has not started yet, this method issues the initial query request.
     * Otherwise, it continues with the saved query locator until all rows are consumed.
     *
     * @return the next batch converted to a list of column maps, or an empty list if no more data is available
     * @throws SalesforceRuntimeException if the Salesforce API call fails
     */
    @Override
    public List<ColumnMap<String, Object>> next() {
        try {
            Map.Entry<List<List<ForceResultField>>, String> resultEntry;
            if (this.neverQueriedMore) {
                this.neverQueriedMore = false;
                resultEntry = partnerService.queryStart(soqlQuery, getRootEntityFieldDefinitions());
            } else if (this.queryMoreLocator != null) {
                resultEntry = partnerService.queryMore(this.queryMoreLocator, getRootEntityFieldDefinitions());
            } else {
                return Collections.emptyList();
            }
            this.queryMoreLocator = resultEntry.getValue();
            List<ColumnMap<String, Object>> result = Collections.synchronizedList(new LinkedList<>());
            Optional.ofNullable(resultEntry.getKey())
                    .orElseGet(Collections::emptyList)
                    .forEach(rec -> result.add(convertToColumnMap(rec)));
            return result;
        } catch (ConnectionException e) {
            throw new SalesforceRuntimeException("Failed to fetch next batch of query results", e);
        }
    }

    /**
     * Applies preprocessing and parameter substitution to a query string.
     *
     * @param query the query to prepare
     * @return the prepared SOQL string
     */
    private String prepareQuery(String query) {
        log.trace("[PrepStat] prepareQuery IMPLEMENTED {}", query);
        query = preprocessQuery(query);
        return setParams(query);
    }

    /**
     * Normalizes supported literal shortcuts before query execution.
     *
     * <p>Currently this method converts supported timestamp escape syntax into Salesforce-compatible SOQL.
     *
     * @param soqlQuery the query to preprocess
     * @return the normalized query, or {@code null} if the input was {@code null}
     */
    private String preprocessQuery(String soqlQuery) {
        // Preprocess some sugar like Date Literals into SOQL format
        // '{ts 2021-10-12 00:00:12Z}'
        // '{ts 2021-10-12T00:00:12Z}'
        if (soqlQuery == null) {
            return soqlQuery;
        }
        String soqlQueryProcessed = soqlQuery;
        if (soqlQuery.contains("{ts")) {
            soqlQueryProcessed = soqlQuery.trim()
                    .replaceAll(
                            "'\\{ts\\s*(\\d{4}-\\d{2}-\\d{2})(T|\\s)(\\d{2}:\\d{2}:\\d{2})(Z|[+-]\\d{3,4}|)(\\.\\d+)?\\s*}'",
                            "$1T$3$4");
        }
        return soqlQueryProcessed;
    }

    /**
     * Converts a Salesforce record representation into a JDBC-friendly column map.
     *
     * <p>Nested collections are flattened, Salesforce field types are resolved to JDBC types,
     * and both physical column names and labels are preserved when available.
     *
     * @param recordFields the raw Salesforce fields for a single record
     * @return the converted row representation
     */
    public ColumnMap<String, Object> convertToColumnMap(List<ForceResultField> recordFields) {
        ColumnMap<String, Object> columnMap = new ColumnMap<>();
        // Flatten not only child records, but also Lists of Lists - for Relations - list of subrecords
        recordFields = flatten(recordFields);
        recordFields.stream()
                .map(field -> field == null ? new ForceResultField() : field)
                .forEach(field -> {
                    TypeInfo typeInfo = TypeInfo.OTHER_TYPE_INFO;
                    if (field.getFieldType() != null) {
                        typeInfo = TypeInfo.lookupTypeInfo(field.getFieldType());
                    }
                    if (typeInfo == TypeInfo.OTHER_TYPE_INFO) {
                        typeInfo = findColumnType(field.getName());
                    }
                    String columnLabel = findColumnLabel(field.getName());
                    columnMap.put(field.getFullName(), columnLabel, field.getValue(), typeInfo);
                });
        return columnMap;
    }

    private TypeInfo findColumnType(String name) {
        if (name == null) {
            return TypeInfo.OTHER_TYPE_INFO;
        }
        try {
            for (int i = 1; i <= metadata.getColumnCount(); i++) {
                if (name.equalsIgnoreCase(metadata.getColumnName(i))) {
                    return TypeInfo.lookupTypeInfo(metadata.getColumnTypeName(i));
                }
            }
            String[] prefix = StringUtils.split(name, '.');
            if (prefix.length > 0) {
                name = String.join(".", List.of(prefix).subList(1, prefix.length));
                for (int i = 1; i <= metadata.getColumnCount(); i++) {
                    if (name.equalsIgnoreCase(metadata.getColumnName(i))) {
                        return TypeInfo.lookupTypeInfo(metadata.getColumnTypeName(i));
                    }
                }
            }
        } catch (SQLException e) {
            // ignore
        }
        return TypeInfo.OTHER_TYPE_INFO;
    }

    private String findColumnLabel(String name) {
        if (name == null) {
            return null;
        }
        try {
            for (int i = 1; i <= metadata.getColumnCount(); i++) {
                if (name.equalsIgnoreCase(metadata.getColumnName(i))) {
                    return metadata.getColumnLabel(i);
                }
            }
        } catch (SQLException e) {
            // ignore
        }
        return name;
    }

    /**
     * Detects the cache mode for a query and removes any leading cache hint.
     *
     * <p>Supported hints are {@code CACHE GLOBAL} and {@code CACHE SESSION}.
     * If no supported hint is present, caching is disabled for the query.
     *
     * @param query the original query string
     */
    protected void setCacheMode(String query) {
        Matcher matcher = CACHE_HINT.matcher(query);
        if (matcher.matches()) {
            String mode = matcher.group(2);
            String hint = matcher.group(1);
            this.soqlQuery = query.replaceFirst(hint, "");
            this.cacheMode = CacheMode.valueOf(mode.toUpperCase());
        } else {
            this.soqlQuery = query;
            this.cacheMode = CacheMode.NO_CACHE;
        }
    }

    /**
     * Computes the cache key for the current prepared query.
     *
     * <p>Global cache keys depend only on the prepared query text, while session cache keys
     * are additionally scoped by the connection unique identifier.
     *
     * @return the hashed cache key
     */
    private String getCacheKey() {
        String preparedQuery = prepareQuery(soqlQuery);
        String key = cacheMode == CacheMode.GLOBAL
                ? preparedQuery
                : connection.getUUID() + preparedQuery;
        return sha256(key);
    }

    private String sha256(final String key) {
        try {
            final MessageDigest digest = MessageDigest.getInstance("SHA-256");
            final byte[] hash = digest.digest(key.getBytes(StandardCharsets.UTF_8));
            final StringBuilder hexString = new StringBuilder();
            for (final byte b : hash) {
                final String hex = Integer.toHexString(0xff & b);
                if (hex.length() == 1) {
                    hexString.append('0');
                }
                hexString.append(hex);
            }
            return hexString.toString();
        } catch (Exception ex) {
            return key;
        }
    }

    /**
     * Returns the bound parameters, padding missing placeholders with {@code null} values if needed.
     *
     * <p>This ensures the parameter list matches the number of {@code ?} placeholders currently
     * present in the query text.
     *
     * @return the internal parameter list
     */
    public List<Object> getParameters() {
        log.trace("[PrepStat] getParameters IMPLEMENTED {}", soqlQuery);
        int paramsCountInQuery = StringUtils.countMatches(soqlQuery, '?');
        log.debug("[PrepStat] getParameters - {}/{} parameters", paramsCountInQuery, parameters.size());
        if (parameters.size() < paramsCountInQuery) {
            parameters.addAll(Collections.nCopies(paramsCountInQuery - parameters.size(), null));
        }
        return parameters;
    }

    /**
     * Replaces JDBC parameter placeholders with Salesforce-safe SOQL literal values.
     *
     * @param soql the query containing {@code ?} placeholders
     * @return the query with all known parameters injected
     */
    protected String setParams(String soql) {
        log.trace("[PrepStat] setParams IMPLEMENTED {}", soql);
        String result = soql;
        for (Object param : getParameters()) {
            String paramRepresentation = SoqlParameterConverter.convertToSoqlParam(param);
            result = result.replaceFirst("\\?", paramRepresentation);
        }
        return result;
    }

    /**
     * Creates a synthetic {@link ResultSetMetaData} instance from a single row.
     *
     * <p>This is primarily useful when metadata must be inferred from already materialized data.
     *
     * @param row the row used to infer metadata
     * @return metadata for the row, or {@code null} if the row is {@code null} or metadata creation fails
     */
    public static ResultSetMetaData createMetaData(ColumnMap<String, Object> row) {
        if (row == null) {
            return null;
        }
        try {
            log.trace("[PrepStat] dummyMetaData IMPLEMENTED");
            RowSetMetaDataImpl result = new RowSetMetaDataImpl();
            int columnsCount = row.size();
            result.setColumnCount(columnsCount);
            for (int i = 1; i <= columnsCount; i++) {
                String fieldName = row.getColumnNames().get(i - 1);
                result.setAutoIncrement(i, false);
                result.setColumnName(i, fieldName);
                result.setColumnLabel(i, fieldName);
                TypeInfo typeInfo = row.getTypes().get(i - 1);
                log.trace(
                        "[PrepStat] createMetaData (" + i + ") " + fieldName + " : " + typeInfo.getTypeName() + " => "
                                + typeInfo.getSqlDataType());
                result.setColumnType(i, typeInfo.getSqlDataType());
                result.setColumnTypeName(i, typeInfo.getTypeName());
                result.setPrecision(i, typeInfo.getPrecision());
                result.setSchemaName(i, ForceDatabaseMetaData.DEFAULT_SCHEMA);
                result.setCatalogName(i, ForceDatabaseMetaData.DEFAULT_CATALOG);
                result.setTableName(i, null);
                result.setCaseSensitive(i, false);
            }
            return result;
        } catch (Exception e) {
            // Ignore for metadata - just return empty
            log.warn("Failed to compile dummy metadata information", e);
            return null;
        }
    }

    private ResultSetMetaData loadMetaData() throws SQLException {
        try {
            log.trace("[PrepStat] loadMetaData IMPLEMENTED");
            if (metadata == null) {
                RowSetMetaDataImpl result = new RowSetMetaDataImpl();
                SoqlQueryAnalyzer analyzer = getSoqlQueryAnalyzer();
                FieldDefTree rootFieldDefinitions = getRootEntityFieldDefinitions();
                List<FieldDef> resultFieldDefinitions = rootFieldDefinitions.flattenInSqlOrder();
                int columnsCount = resultFieldDefinitions.size();
                result.setColumnCount(columnsCount);
                for (int i = 1; i <= columnsCount; i++) {
                    FieldDef field = resultFieldDefinitions.get(i - 1);
                    result.setAutoIncrement(i, false);
                    result.setColumnName(i, field.getFullName());
                    result.setColumnLabel(i, field.getAlias());
                    String forceTypeName = field.getType();
                    TypeInfo typeInfo = TypeInfo.lookupTypeInfo(forceTypeName);
                    result.setColumnType(i, typeInfo.getSqlDataType());
                    result.setColumnTypeName(i, typeInfo.getTypeName());
                    result.setPrecision(i, typeInfo.getPrecision());
                    result.setSchemaName(i, ForceDatabaseMetaData.DEFAULT_SCHEMA);
                    result.setCatalogName(i, ForceDatabaseMetaData.DEFAULT_CATALOG);
                    result.setTableName(i, analyzer.getFromObjectName());
                    result.setCaseSensitive(i, false);
                }
                metadata = result;
            }
            return metadata;
        } catch (RuntimeException e) {
            throw new SQLException(e.getCause() != null ? e.getCause() : e);
        }
    }

    private <T> List<T> flatten(List<T> listWithLists) {
        return listWithLists.stream()
                .flatMap(
                        def -> def instanceof Collection
                                ? flatten((List<T>) def).stream() // MultiLevel flattening
                                : Stream.of(def)
                ).toList();
    }

    /**
     * Returns the parsed field definition tree for the root entity of the current SOQL query.
     *
     * @return the root field definition tree
     */
    public FieldDefTree getRootEntityFieldDefinitions() {
        log.trace("[PrepStat] getFieldDefinitions IMPLEMENTED ");
        if (fieldDefinitions == null) {
            fieldDefinitions = getSoqlQueryAnalyzer().getFieldDefinitions();
            log.debug("[PrepStat] getFieldDefinitions:\n {}", fieldDefinitions.toTree());
        }
        return fieldDefinitions;
    }

    private QueryAnalyzer getQueryAnalyzer() {
        if (queryAnalyzer == null) {
            queryAnalyzer = new QueryAnalyzer(soqlQuery, this::runResolveSubselect, partnerService);
        }
        return queryAnalyzer;
    }

    private SoqlQueryAnalyzer getSoqlQueryAnalyzer() {
        if (soqlQueryAnalyzer == null) {
            soqlQueryAnalyzer = new SoqlQueryAnalyzer(getQueryAnalyzer());
            if (soqlQueryAnalyzer.isExpandedStarSyntaxForFields()) {
                this.soqlQuery = soqlQueryAnalyzer.getSoqlQueryString();
                log.debug("[PrepStat] Expanded Star Syntax to {}", soqlQuery);
            }
        }
        return soqlQueryAnalyzer;
    }

    private List<Map<String, Object>> runResolveSubselect(String soql, List<Object> parameters) {
        List<Map<String, Object>> results = new ArrayList<>();
        log.debug("Resolving subselect \n{}", soql);
        try {
            ForcePreparedStatement forcePreparedStatement = new ForcePreparedStatement(connection, soql);
            forcePreparedStatement.addParameters(parameters);
            ResultSet rs = forcePreparedStatement.query();

            while (rs.next()) {
                // LinkedHashMap is needed to save the order of the fields
                Map<String, Object> rec = new LinkedHashMap<>();
                results.add(rec);
                for (int i = 0; i < rs.getMetaData().getColumnCount(); i++) {
                    rec.put(rs.getMetaData().getColumnName(i + 1), rs.getString(i + 1));
                }
            }
            log.debug("  {} records resolved with {} columns", results.size(), rs.getMetaData().getColumnCount());
        } catch (Exception e) {
            log.warn("Failed to resolve sub-select \n{}", soql, e);
            this.warnings.addSuppressed(new SQLWarning("Failed to resolve sub-select \n" + soql, e));
            throw new IllegalArgumentException("Failed to resolve sub-select: " + e.getMessage());
        }

        return results;
    }

    /**
     * Returns parameter metadata for the current query and currently bound values.
     *
     * @return the parameter metadata
     */
    @Override
    public ParameterMetaData getParameterMetaData() {
        return new ParameterMetadataImpl(parameters, soqlQuery);
    }

    /**
     * Returns metadata for the current query result.
     *
     * <p>When caching is enabled, metadata may be reused from cached results.
     *
     * @return the result set metadata
     * @throws SQLException if metadata cannot be resolved
     */
    public ResultSetMetaData getMetaData() throws SQLException {
        log.trace("[PrepStat] getMetaData IMPLEMENTED ");
        return cacheMode == CacheMode.NO_CACHE
                ? loadMetaData()
                : loadFromMetaDataCache();
    }

    private ResultSetMetaData loadFromMetaDataCache() throws SQLException {
        String key = getCacheKey();
        if (dataCache.containsKey(key)) {
            CachedResultSet value = dataCache.get(key);
            value.beforeFirst();
            return value.getMetaData();
        }

        ResultSetMetaData value;
        value = loadMetaData();

        this.metadata = value;
        return value;
    }

    /**
     * Executes the query or loads it from cache and returns a resettable result set.
     *
     * @return the cached or freshly loaded result set
     * @throws SQLException if execution or caching fails
     */
    private synchronized ResultSet loadFromDataCache() throws SQLException {
        CachedResultSet value;
        String key = getCacheKey();
        if (dataCache.containsKey(key)) {
            value = dataCache.get(key);
            value.beforeFirst();
            return value;
        }

        value = query();
        dataCache.put(key, value);
        return value;
    }

    /**
     * Reconnects the underlying connection using new credentials.
     *
     * <p>After reconnecting, the statement refreshes its internal {@link PartnerService} reference
     * so subsequent executions use the updated Salesforce session.
     *
     * @param url the Salesforce JDBC URL
     * @param userName the new user name
     * @param userPass the new password or token-based credential
     * @return {@code true} if the reconnect succeeded
     * @throws ConnectionException if the reconnect fails
     */
    public boolean reconnect(String url, String userName, String userPass) throws ConnectionException {
        log.trace("[PrepStat] RECONNECT IMPLEMENTED newUserName={} url={}", userName, ForceDriver.sanitizeUrl(url));
        boolean updated = connection.updatePartnerConnection(url, userName, userPass);
        this.partnerService = connection.getPartnerService();
        return updated;
    }

    /**
     * Sets the fetch size hint.
     *
     * <p>This value is stored by the statement but may not directly control Salesforce fetch behavior.
     *
     * @param rows the requested fetch size
     */
    @Override
    public void setFetchSize(int rows) {
        this.fetchSize = rows;
    }

    /**
     * Returns the configured fetch size hint.
     *
     * @return the fetch size
     */
    @Override
    public int getFetchSize() {
        return fetchSize;
    }

    /**
     * Sets the maximum number of rows hint.
     *
     * @param max the maximum number of rows
     */
    @Override
    public void setMaxRows(int max) {
        this.maxRows = max;
    }

    /**
     * Returns the configured maximum rows hint.
     *
     * @return the maximum rows value
     */
    @Override
    public int getMaxRows() {
        return maxRows;
    }

    private void addParameters(List<Object> parameters) {
        this.parameters.addAll(parameters);
    }

    /**
     * Adds a single positional parameter to the internal parameter list.
     *
     * <p>If required, the list is padded with {@code null} values so the supplied position is valid.
     *
     * @param parameterIndex the 1-based JDBC parameter index
     * @param x the value to bind
     */
    protected void addParameter(int parameterIndex, Object x) {
        log.trace("[PrepStat] addParameter {} IMPLEMENTED", parameterIndex);
        parameterIndex--;
        if (parameters.size() < parameterIndex) {
            parameters.addAll(Collections.nCopies(parameterIndex - parameters.size(), null));
        }
        parameters.add(parameterIndex, x);
    }

    @Override
    public void setBigDecimal(int parameterIndex, BigDecimal x) {
        addParameter(parameterIndex, x);
    }

    @Override
    public void setBoolean(int parameterIndex, boolean x) {
        addParameter(parameterIndex, x);
    }

    @Override
    public void setByte(int parameterIndex, byte x) {
        addParameter(parameterIndex, x);
    }

    @Override
    public void setDate(int parameterIndex, Date x) {
        addParameter(parameterIndex, x);
    }

    @Override
    public void setDouble(int parameterIndex, double x) {
        addParameter(parameterIndex, x);
    }

    @Override
    public void setFloat(int parameterIndex, float x) {
        addParameter(parameterIndex, x);
    }

    @Override
    public void setInt(int parameterIndex, int x) {
        addParameter(parameterIndex, x);
    }

    @Override
    public void setLong(int parameterIndex, long x) {
        addParameter(parameterIndex, x);
    }

    @Override
    public void setNull(int parameterIndex, int sqlType) {
        addParameter(parameterIndex, null);
    }

    @Override
    public void setNull(int paramIndex, int sqlType, String typeName) {
        addParameter(paramIndex, null);
    }

    @Override
    public void setObject(int parameterIndex, Object x) {
        addParameter(parameterIndex, x);
    }

    @Override
    public void setObject(int parameterIndex, Object x, int targetSqlType) {
        addParameter(parameterIndex, x);
    }

    @Override
    public void setObject(int parameterIndex, Object x, int targetSqlType, int scaleOrLength) {
        addParameter(parameterIndex, x);
    }

    @Override
    public void setShort(int parameterIndex, short x) {
        addParameter(parameterIndex, x);
    }

    @Override
    public void setString(int parameterIndex, String x) {
        addParameter(parameterIndex, x);
    }

    @Override
    public void setTime(int parameterIndex, Time x) {
        addParameter(parameterIndex, x);
    }

    @Override
    public void setTimestamp(int parameterIndex, Timestamp x) {
        addParameter(parameterIndex, x);
    }

    /**
     * Executes the given SOQL string as a query.
     *
     * @param sql the query to execute
     * @return the resulting {@link ResultSet}
     * @throws SQLException if execution fails
     */
    @Override
    public ResultSet executeQuery(String sql) throws SQLException {
        log.trace("[PrepStat] executeQuery IMPLEMENTED {}", sql);
        this.soqlQuery = sql;
        this.resultSet = executeQuery();
        return this.resultSet;
    }

    /**
     * Executes the given statement as an update operation.
     *
     * @param sql the statement to execute
     * @return the resulting update count
     * @throws SQLException if execution fails
     */
    @Override
    public int executeUpdate(String sql) throws SQLException {
        return executeUpdate(sql, this.autoGeneratedKeys);
    }

    /**
     * Closes this statement.
     *
     * <p>This implementation clears bound parameters but does not explicitly close the underlying connection.
     */
    @Override
    public void close() {
        parameters.clear();
    }

    /**
     * Returns statement warnings.
     *
     * <p>If a result set exists, warnings are delegated to it; otherwise statement-local warnings are returned.
     *
     * @return the warnings chain, possibly empty
     * @throws SQLException if warning retrieval fails
     */
    @Override
    public SQLWarning getWarnings() throws SQLException {
        return resultSet != null ? resultSet.getWarnings() : warnings;
    }

    /**
     * Clears statement and result set warnings.
     *
     * @throws SQLException if warning cleanup fails
     */
    @Override
    public void clearWarnings() throws SQLException {
        if (resultSet != null) {
            resultSet.clearWarnings();
        }
        warnings = new SQLWarning();
    }

    /**
     * Executes the supplied SQL string and returns whether the first result is a {@link ResultSet}.
     *
     * @param sql the statement to execute
     * @return {@code true} if the execution produced a result set, {@code false} otherwise
     * @throws SQLException if execution fails
     */
    @Override
    public boolean execute(String sql) throws SQLException {
        log.trace("[PrepStat] execute IMPLEMENTED {}", sql);
        this.updateCount = -1;
        this.updateCountReturned = false;
        this.soqlQuery = sql;
        this.resultSet = executeQuery();
        this.resultSetReturned = false;
        boolean result = this.updateCount < 0;
        log.trace("[PrepStat] execute IMPLEMENTED ({}){}", result, sql);
        return result;
    }

    /**
     * Returns the current result set once.
     *
     * <p>To mimic JDBC result consumption semantics, subsequent calls after the first successful retrieval
     * return {@code null}.
     *
     * @return the current result set, or {@code null} if no result set is available or it was already returned
     */
    @Override
    public ResultSet getResultSet() {
        ResultSet toReturn = updateCount < 0 ? resultSet : null;
        if (this.resultSetReturned) {
            log.trace("[PrepStat] getResultSet IMPLEMENTED Already Returned {}\n {}{}",
                    soqlQuery,
                    (resultSet == null ? " resultSet is NULL" : "resultSet is present"),
                    (toReturn == null ? " -> Not to be returned" : " -> Returning"));
            return null;
        }
        this.resultSetReturned = true;
        log.trace("[PrepStat] getResultSet IMPLEMENTED {}\n {}{}",
                soqlQuery,
                (resultSet == null ? " resultSet is NULL" : "resultSet is present"),
                (toReturn == null ? " -> Not to be returned" : " -> Returning"));
        return toReturn;
    }

    /**
     * Returns the current update count once.
     *
     * <p>After the first retrieval, subsequent calls return {@code -1}.
     *
     * @return the current update count, or {@code -1} if already consumed
     */
    @Override
    public int getUpdateCount() {
        if (this.updateCountReturned) {
            log.trace("[PrepStat] getUpdateCount Already Returned {} IMPLEMENTED", updateCount);
            return -1;
        }
        log.trace("[PrepStat] getUpdateCount {} IMPLEMENTED", updateCount);
        this.updateCountReturned = true;
        return updateCount;
    }

    /**
     * Advances to the next available result.
     *
     * <p>For query results this implementation advances the current result set cursor by one row.
     * For update operations it always returns {@code false}.
     *
     * @return {@code true} if another result is available
     * @throws SQLException if cursor movement fails
     */
    @Override
    public boolean getMoreResults() throws SQLException {
        if (updateCount >= 0) {
            log.trace("[PrepStat] getMoreResults IMPLEMENTED (false) updateCount={} sql={}", updateCount, soqlQuery);
            return false;
        }
        boolean more = resultSet != null && resultSet.next();
        log.trace("[PrepStat] getMoreResults IMPLEMENTED ({}) updateCount={} sql={}", more, updateCount, soqlQuery);
        return more;
    }

    /**
     * Sets the fetch direction hint for this statement.
     *
     * @param direction the desired fetch direction
     * @throws SQLException if the direction is not one of the JDBC-supported constants
     */
    @Override
    public void setFetchDirection(int direction) throws SQLException {
        if (direction != ResultSet.FETCH_FORWARD && direction != ResultSet.FETCH_REVERSE
                && direction != ResultSet.FETCH_UNKNOWN) {
            throw new SQLException("Unsupported direction: " + direction);
        } else {
            this.fetchDirection = direction;
        }
    }

    /**
     * Returns the configured fetch direction hint.
     *
     * @return the fetch direction
     */
    @Override
    public int getFetchDirection() {
        return this.fetchDirection;
    }

    /**
     * Returns the owning JDBC connection.
     *
     * @return the parent {@link Connection}
     */
    @Override
    public Connection getConnection() {
        return connection;
    }

    /**
     * Returns generated keys for the last execution.
     *
     * <p>Generated keys are available only if the statement was created or executed with
     * {@link Statement#RETURN_GENERATED_KEYS}.
     *
     * @return the result set containing generated keys
     * @throws SQLException if generated keys were not requested
     */
    @Override
    public ResultSet getGeneratedKeys() throws SQLException {
        if (autoGeneratedKeys != Statement.RETURN_GENERATED_KEYS) {
            throw new SQLException(
                    "Cannot return generated keys: query was not set with Statement.RETURN_GENERATED_KEYS");
        }

        return this.resultSet;
    }

    /**
     * Executes the given statement with the provided generated keys mode.
     *
     * @param sql the statement to execute
     * @param autoGeneratedKeys generated keys flag as defined by {@link Statement}
     * @return the resulting update count
     * @throws SQLException if execution fails
     */
    @Override
    public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
        executeInternal(sql, autoGeneratedKeys);
        return this.updateCount;
    }

    /**
     * Executes the given statement and ignores the requested generated column indexes.
     *
     * @param sql the statement to execute
     * @param columnIndexes requested generated column indexes
     * @return the resulting update count
     * @throws SQLException if execution fails
     */
    @Override
    public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
        return executeUpdate(sql);
    }

    /**
     * Executes the given statement and ignores the requested generated column names.
     *
     * @param sql the statement to execute
     * @param columnNames requested generated column names
     * @return the resulting update count
     * @throws SQLException if execution fails
     */
    @Override
    public int executeUpdate(String sql, String[] columnNames) throws SQLException {
        return executeUpdate(sql);
    }

    /**
     * Executes the given statement and returns whether at least one row was affected.
     *
     * @param sql the statement to execute
     * @param autoGeneratedKeys generated keys flag
     * @return {@code true} if the update count is greater than zero
     * @throws SQLException if execution fails
     */
    @Override
    public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
        return executeUpdate(sql) > 0;
    }

    /**
     * Executes the given statement and ignores the requested generated column indexes.
     *
     * @param sql the statement to execute
     * @param columnIndexes requested generated column indexes
     * @return {@code true} if the update count is greater than zero
     * @throws SQLException if execution fails
     */
    @Override
    public boolean execute(String sql, int[] columnIndexes) throws SQLException {
        return executeUpdate(sql) > 0;
    }

    /**
     * Executes the given statement and ignores the requested generated column names.
     *
     * @param sql the statement to execute
     * @param columnNames requested generated column names
     * @return {@code true} if the update count is greater than zero
     * @throws SQLException if execution fails
     */
    @Override
    public boolean execute(String sql, String[] columnNames) throws SQLException {
        return executeUpdate(sql) > 0;
    }

    /**
     * Attempts to unwrap this statement to the requested interface.
     *
     * @param iface the interface to unwrap to
     * @param <T> the target type
     * @return this instance cast to {@code iface}, or {@code null} if incompatible
     */
    @Override
    public <T> T unwrap(Class<T> iface) {
        return iface.isInstance(this) ? iface.cast(this) : null;
    }

    /**
     * Returns whether this statement implements the requested interface.
     *
     * @param iface the interface to test
     * @return {@code true} if this instance is assignable to {@code iface}
     */
    @Override
    public boolean isWrapperFor(Class<?> iface) {
        return iface.isInstance(this);
    }

    /**
     * Executes the current query as an update operation.
     *
     * @return the resulting update count
     * @throws SQLException if execution fails
     */
    @Override
    public int executeUpdate() throws SQLException {
        return executeUpdate(soqlQuery);
    }

    /**
     * Clears all currently bound parameters.
     */
    @Override
    public void clearParameters() {
        parameters.clear();
    }

    /**
     * Executes the current query using the current generated keys configuration.
     *
     * @return always {@code true} after execution
     * @throws SQLException if execution fails
     */
    @Override
    public boolean execute() throws SQLException {
        executeInternal(soqlQuery, autoGeneratedKeys);
        return true;
    }

    /**
     * Binds a national character string parameter.
     *
     * <p>This implementation delegates to {@link #setString(int, String)}.
     *
     * @param parameterIndex the 1-based parameter index
     * @param value the value to bind
     */
    @Override
    public void setNString(int parameterIndex, String value) {
        setString(parameterIndex, value);
    }

}
