package com.ascendix.jdbc.salesforce.statement.processor;

import com.ascendix.jdbc.salesforce.delegates.PartnerService;
import com.ascendix.jdbc.salesforce.resultset.CachedResultSet;
import com.ascendix.jdbc.salesforce.resultset.CommandLogCachedResultSet;
import com.ascendix.jdbc.salesforce.statement.ForcePreparedStatement;
import com.sforce.soap.partner.IError;
import com.sforce.soap.partner.ISaveResult;
import com.sforce.ws.ConnectionException;
import java.util.Arrays;
import java.util.stream.Collectors;
import lombok.extern.slf4j.Slf4j;

@Slf4j
public class InsertQueryProcessor {

    public static CachedResultSet processQuery(ForcePreparedStatement statement, String soqlQuery,
        PartnerService partnerService, InsertQueryAnalyzer insertQueryAnalyzer) {
        CommandLogCachedResultSet resultSet = new CommandLogCachedResultSet();
        if (soqlQuery == null || soqlQuery.trim().isEmpty()) {
            resultSet.log("No INSERT query found");
            return resultSet;
        }

        try {
            int updateCount = 0;
            String fromObjectName = insertQueryAnalyzer.getFromObjectName();
            ISaveResult[] records = partnerService.createRecords(fromObjectName, insertQueryAnalyzer.getRecords());

            for (ISaveResult result : records) {
                if (result.isSuccess()) {
                    if (statement.hasAutoGeneratedKeys()) {
                        resultSet.log(fromObjectName + " created with Id=" + result.getId(), result.getId());
                    } else {
                        resultSet.log(fromObjectName + " created with Id=" + result.getId());
                    }
                    updateCount++;
                } else {
                    resultSet.addWarning(fromObjectName + " failed to create with error="
                        + Arrays.stream(result.getErrors()).map(IError::getMessage).collect(Collectors.joining(",")));
                }
            }
            statement.setUpdateCount(updateCount);
            statement.setResultSet(resultSet);
        } catch (ConnectionException e) {
            resultSet.addWarning("Failed request to create entities with error: " + e.getMessage());
            log.error("Failed request to create entities with error: {}", e.getMessage(), e);
        }
        return resultSet;
    }
}
